In [1]:
import numpy as np

In [4]:
for i in range(10):
    np.random.seed()
    print(np.random.randint(0, 100, 10))


[16 87 93 24 83 57 35 46 50 39]
[88 35 73 64 59  0 86 37 28 53]
[77 66  9 26 32 91 71 58 12 48]
[27 39 42 55 85 63  6 18 60 25]
[ 4 94 75  7 49  8 44 38 91 31]
[27  7 78 97 94 15  8 55 67 31]
[87 23 42 15 33 11 68 61 43 99]
[18 62 84 86 25  0 90 34 85 61]
[87 64 41 95 96 15 76 84 84 55]
[50  5 76 68 70 32 30 47  4 75]
